import { StyleSheet } from 'react-native';

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    height: '100%',
    overflow: 'hidden',
  },
  // Sidebar Styles
  sidebar: {
    width: 280,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1,
    borderRightColor: '#E2E8F0',
    flexDirection: 'column',
    height: '100%',
  },
  sidebarCollapsed: {
    width: 60,
  },
  sidebarHeader: {
    height: 48,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sidebarHeaderCollapsed: {
    paddingHorizontal: 0,
    justifyContent: 'center',
  },
  sidebarHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sidebarHeaderTitle: {
    fontSize: 13,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  sourceSwitchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  sourceSwitchBtnActive: {
    backgroundColor: '#F0F9FF',
    borderColor: '#BAE6FD',
  },
  sourceSwitchText: {
    fontSize: 11,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  collapseBtn: {
    width: 26,
    height: 26,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchBox: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 8,
    height: 32,
  },
  searchInput: {
    flex: 1,
    fontSize: 11.5,
    fontFamily: 'Krasar-Regular',
    color: '#0F172A',
    paddingVertical: 0,
  },
  addContactBtn: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BAE6FD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  folderScroll: {
    maxHeight: 38,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  folderScrollContent: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  folderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 5,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  folderChipActive: {
    backgroundColor: '#F0F9FF',
    borderColor: '#BAE6FD',
  },
  folderChipText: {
    fontSize: 10,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  folderChipTextActive: {
    color: '#0284C7',
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
  },
  folderCountBadge: {
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    paddingHorizontal: 4,
    paddingVertical: 0.5,
  },
  folderCountBadgeActive: {
    backgroundColor: '#0284C7',
  },
  folderCountText: {
    fontSize: 8.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#64748B',
  },
  folderCountTextActive: {
    color: '#FFFFFF',
  },
  convList: {
    flex: 1,
  },
  convCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  convCardActive: {
    backgroundColor: '#F0F9FF',
  },
  collapsedItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    position: 'relative',
  },
  collapsedItemActive: {
    backgroundColor: '#F0F9FF',
  },
  activePillDot: {
    position: 'absolute',
    left: 2,
    top: '50%',
    marginTop: -4,
    width: 3,
    height: 8,
    borderRadius: 1.5,
    backgroundColor: '#0284C7',
  },
  convBody: {
    flex: 1,
    justifyContent: 'center',
  },
  convTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  convTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginRight: 6,
  },
  convTitle: {
    fontSize: 12,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
    flexShrink: 1,
  },
  convTitleActive: {
    color: '#0284C7',
  },
  convTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  convTime: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  convSnippetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  convSnippetLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  convSnippet: {
    fontSize: 11,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
    flex: 1,
  },
  convSnippetWithMedia: {
    color: '#0284C7',
  },
  tgMiniThumbRow: {
    width: 14,
    height: 14,
    borderRadius: 3,
    overflow: 'hidden',
  },
  tgMiniThumbImg: {
    width: '100%',
    height: '100%',
  },
  tgUnreadBadge: {
    backgroundColor: '#0284C7',
    borderRadius: 10,
    minWidth: 17,
    height: 17,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  tgUnreadBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
  },
  tgPinBadge: {
    padding: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarBottomBar: {
    height: 44,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
  },
  sidebarBottomTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  sidebarBottomBarCollapsed: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  sidebarBottomTabCollapsed: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 8,
  },
  // Main Chat Column
  chatMain: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#F8FAFC',
    height: '100%',
  },
  detailHeader: {
    height: 48,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  detailTitle: {
    fontSize: 13,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  detailSub: {
    fontSize: 10,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
    marginTop: 1,
  },
  detailSubOnline: {
    color: '#16A34A',
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
  },
  detailHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionBtnActive: {
    backgroundColor: '#F0F9FF',
    borderColor: '#BAE6FD',
  },
  // Pinned Message Banner
  pinnedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingVertical: 6,
    gap: 8,
  },
  pinnedAccentBar: {
    width: 3,
    height: 24,
    borderRadius: 1.5,
    backgroundColor: '#0284C7',
  },
  pinnedInfo: {
    flex: 1,
  },
  pinnedLabel: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  pinnedText: {
    fontSize: 11,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  // Message Feed
  feedContainer: {
    flex: 1,
    position: 'relative',
  },
  messagesScroll: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 6,
  },
  dateSeparatorRow: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  dateSeparatorBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 12,
    paddingVertical: 3,
    borderRadius: 12,
  },
  dateSeparatorText: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    color: '#475569',
  },
  msgRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    marginBottom: 4,
    maxWidth: '90%',
    alignSelf: 'flex-start',
  },
  msgRowMe: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
  },
  msgBubbleColumn: {
    flexDirection: 'column',
    flexShrink: 1,
    minWidth: 0,
  },
  msgBubble: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
  },
  msgBubbleMe: {
    backgroundColor: '#EFFCEE',
    borderColor: '#BBF7D0',
  },
  msgBubbleOther: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
  },
  msgBubbleSticker: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  msgBubblePhoto: {
    padding: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    overflow: 'hidden',
    width: 400,
    maxWidth: '100%',
    borderRadius: 14,
  },
  msgBubbleWithCaption: {
    padding: 3,
    paddingHorizontal: 3,
    paddingVertical: 3,
    overflow: 'hidden',
    width: 400,
    maxWidth: '100%',
    borderRadius: 14,
    borderWidth: 1,
  },
  msgBubbleVoice: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    minWidth: 230,
  },
  msgSenderName: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
    marginBottom: 2,
  },
  tgForwardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 3,
  },
  tgForwardLabel: {
    fontSize: 11,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  tgForwardLabelMe: {
    color: '#475569',
  },
  tgForwardSender: {
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  tgForwardSenderMe: {
    color: '#0369A1',
  },
  msgText: {
    fontSize: 12.5,
    fontFamily: 'Krasar-Regular',
    color: '#0F172A',
    lineHeight: 17.5,
  },
  msgTextMe: {
    color: '#0F172A',
  },
  tgCaptionTextBox: {
    paddingHorizontal: 6,
    paddingTop: 6,
    paddingBottom: 4,
  },
  tgMsgMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 3,
    marginTop: 2,
  },
  tgEditedLabel: {
    fontSize: 8.5,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  tgMsgTime: {
    fontSize: 9,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  tgMsgTimeMe: {
    color: '#16A34A',
  },
  // Photos full-bleed
  tgPhotoContainer: {
    width: '100%',
    height: 250,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F1F5F9',
  },
  tgPhotoImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  tgPhotoMetaPill: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3.5,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  tgPhotoTimeText: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Regular',
    color: '#FFFFFF',
  },
  tgPhotoCaptionContainer: {
    width: '100%',
    height: 230,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
  },
  tgPhotoImageWithCaption: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  // Video player card
  tgVideoContainer: {
    width: '100%',
    height: 250,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#0F172A',
  },
  tgVideoPlayOverlay: {
    ...({
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
    } as any),
  },
  tgVideoPlayBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  tgVideoDurationBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  tgVideoDurationText: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Bold',
    color: '#FFFFFF',
  },
  // Multi-photo Album Collage
  tgAlbumCollage: {
    width: '100%',
    backgroundColor: 'transparent',
    gap: 3,
  },
  tgAlbumCollageWithCaption: {
    borderRadius: 0,
  },
  tgAlbumRow: {
    flexDirection: 'row',
    gap: 3,
    width: '100%',
  },
  tgAlbumCell: {
    flex: 1,
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 4,
    backgroundColor: '#0F172A',
  },
  tgAlbumImage: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
  },
  tgAlbumMoreOverlay: {
    ...({
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      alignItems: 'center',
      justifyContent: 'center',
    } as any),
  },
  tgAlbumMoreText: {
    fontSize: 22,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // Telegram Desktop Fullscreen Photo Lightbox
  lightboxModal: {
    ...({
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100vw',
      height: '100vh',
      backgroundColor: 'rgba(0, 0, 0, 0.94)',
      zIndex: 999999,
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
    } as any),
  },
  lightboxTopBar: {
    width: '100%',
    height: 52,
    paddingLeft: 80,
    paddingRight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    zIndex: 1000000,
  },
  lightboxActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxBackdrop: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  lightboxImage: {
    maxWidth: '92%',
    maxHeight: '90%',
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  // Voice note
  tgVoiceMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
  },
  tgVoicePlayBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tgVoicePlayBtnMe: {
    backgroundColor: '#16A34A',
  },
  tgVoicePlayBtnOther: {
    backgroundColor: '#0284C7',
  },
  tgVoiceRightCol: {
    flex: 1,
    gap: 4,
  },
  tgVoiceWaveTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    height: 18,
  },
  tgWaveBar: {
    width: 2,
    borderRadius: 1,
  },
  tgWaveBarMe: {
    backgroundColor: '#BBF7D0',
  },
  tgWaveBarMePlayed: {
    backgroundColor: '#16A34A',
  },
  tgWaveBarOther: {
    backgroundColor: '#CBD5E1',
  },
  tgWaveBarOtherPlayed: {
    backgroundColor: '#0284C7',
  },
  tgVoiceMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  tgVoiceDuration: {
    fontSize: 11,
    fontFamily: 'Krasar-Bold',
    color: '#64748B',
    fontWeight: '700',
  },
  tgVoiceDurationMe: {
    color: '#16A34A',
  },
  tgVoiceTimeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tgVoiceTimeText: {
    fontSize: 9,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  tgVoiceTimeTextMe: {
    color: '#16A34A',
  },
  // Document File
  tgFileBubbleBlock: {
    paddingVertical: 2,
    paddingHorizontal: 2,
    minWidth: 220,
  },
  tgFileMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tgDownloadCircleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0284C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tgFileInfoBox: {
    flex: 1,
  },
  tgFileName: {
    fontSize: 12,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  tgFileSizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  tgFileSize: {
    fontSize: 10,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  tgFileDot: {
    fontSize: 10,
    color: '#CBD5E1',
  },
  tgFileDownloadLink: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    color: '#0284C7',
  },
  // Stickers
  tgStickerBox: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
    minHeight: 120,
    padding: 4,
  },
  tgStickerImage: {
    width: 140,
    height: 140,
  },
  tgStickerEmojiText: {
    fontSize: 56,
    lineHeight: 64,
  },
  // Quotes
  tgQuoteBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.03)',
    borderRadius: 4,
    marginBottom: 4,
    overflow: 'hidden',
  },
  tgQuoteBoxMe: {
    backgroundColor: 'rgba(22, 163, 74, 0.08)',
  },
  tgQuoteBoxOther: {
    backgroundColor: 'rgba(2, 132, 199, 0.08)',
  },
  tgQuoteAccent: {
    width: 3,
    backgroundColor: '#0284C7',
  },
  tgQuoteAccentMe: {
    backgroundColor: '#16A34A',
  },
  tgQuoteAccentOther: {
    backgroundColor: '#0284C7',
  },
  tgQuoteBody: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    flex: 1,
  },
  tgQuoteSender: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  tgQuoteSenderMe: {
    color: '#16A34A',
  },
  tgQuoteText: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  tgQuoteTextMe: {
    color: '#334155',
  },
  // Reactions
  tgReactionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 3,
  },
  tgReactionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1.5,
  },
  tgReactionPillChosen: {
    backgroundColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  tgReactionEmoji: {
    fontSize: 11,
  },
  tgReactionCount: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Bold',
    color: '#64748B',
  },
  // Floating bottom scroll
  floatingScrollBottomBtn: {
    position: 'absolute',
    bottom: 12,
    right: 16,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Input Section
  inputBar: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 10,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  inputCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  inputCardFocused: {
    borderColor: '#0284C7',
    backgroundColor: '#FFFFFF',
  },
  inputCardRecording: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  textInput: {
    fontSize: 12.5,
    fontFamily: 'Krasar-Regular',
    color: '#0F172A',
    minHeight: 34,
    maxHeight: 120,
    padding: 0,
  },
  inputToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  toolbarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  toolIconBtn: {
    width: 26,
    height: 26,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolIconBtnActive: {
    backgroundColor: '#E2E8F0',
  },
  toolIconBtnAi: {
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#E0E7FF',
  },
  toolIconBtnAiActive: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  toolIconBtnRecording: {
    backgroundColor: '#FEE2E2',
  },
  aiMarkupBar: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 8,
    marginBottom: 6,
    gap: 6,
  },
  aiMarkupTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  aiMarkupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  aiMarkupTitleText: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#4338CA',
  },
  aiFormatGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  aiFormatBtn: {
    width: 22,
    height: 22,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiFormatBtnText: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#475569',
  },
  aiActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 5,
  },
  aiActionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  aiActionChipActive: {
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
  },
  aiActionChipText: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#3730A3',
  },
  // Seen Info Modal Styles
  seenModalContent: {
    gap: 12,
    paddingVertical: 4,
  },
  seenMessagePreviewCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
    gap: 4,
  },
  seenPreviewSenderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  seenPreviewSender: {
    fontSize: 11,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  seenPreviewTime: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  seenPreviewText: {
    fontSize: 11.5,
    fontFamily: 'Krasar-Regular',
    color: '#475569',
    lineHeight: 16,
  },
  seenStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  seenStatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  seenStatText: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  seenListTitle: {
    fontSize: 11.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 2,
  },
  seenParticipantsScroll: {
    maxHeight: 220,
  },
  seenParticipantItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  seenParticipantInfo: {
    flex: 1,
  },
  seenParticipantName: {
    fontSize: 11.5,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  seenParticipantTime: {
    fontSize: 10,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
  },
  recordingPulseDot: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#EF4444',
  },
  toolbarRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sendBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#0284C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: '#CBD5E1',
  },
  replyPreviewBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginBottom: 6,
    gap: 8,
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  replyPreviewAccent: {
    width: 3,
    height: 22,
    borderRadius: 1.5,
    backgroundColor: '#0284C7',
  },
  replyPreviewInfo: {
    flex: 1,
  },
  replyPreviewSender: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  replyPreviewText: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  editPreviewBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginBottom: 6,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  editPreviewInfo: {
    flex: 1,
  },
  editPreviewLabel: {
    fontSize: 10,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0284C7',
  },
  editPreviewText: {
    fontSize: 10.5,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
  },
  attachmentsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 6,
  },
  attachmentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F1F5F9',
    borderRadius: 5,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  attachmentName: {
    fontSize: 10,
    fontFamily: 'Krasar-Regular',
    color: '#0F172A',
    maxWidth: 120,
  },
  emojiPickerContainer: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    padding: 10,
    maxHeight: 180,
  },
  emojiPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  emojiPickerTitle: {
    fontSize: 11,
    fontFamily: 'Krasar-Bold',
    color: '#64748B',
  },
  emojiScroll: {
    flex: 1,
  },
  emojiCatSection: {
    marginBottom: 8,
  },
  emojiCatTitle: {
    fontSize: 9.5,
    fontFamily: 'Krasar-Bold',
    color: '#94A3B8',
    marginBottom: 4,
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  emojiCell: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  emojiText: {
    fontSize: 16,
  },
  // Empty State & Connect
  emptyStateBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 8,
  },
  emptyStateIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyTitle: {
    fontSize: 14,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  emptySub: {
    fontSize: 11.5,
    fontFamily: 'Krasar-Regular',
    color: '#94A3B8',
    textAlign: 'center',
    maxWidth: 280,
  },
  heroCenterCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    gap: 10,
  },
  heroIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BAE6FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: 16,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#0F172A',
  },
  heroSub: {
    fontSize: 12,
    fontFamily: 'Krasar-Regular',
    color: '#64748B',
    textAlign: 'center',
    maxWidth: 320,
    lineHeight: 18,
  },
  heroActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#0284C7',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 7,
    marginTop: 6,
  },
  heroActionBtnText: {
    fontSize: 12,
    fontFamily: 'Krasar-Bold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // Floating Bubble Action Tooltip
  msgTooltipBar: {
    position: 'absolute',
    top: -30,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 2,
    zIndex: 50,
  },
  msgTooltipBarLeft: {
    right: 'auto',
    left: 0,
  },
  msgTooltipEmojiBtn: {
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 4,
  },
  msgTooltipEmojiText: {
    fontSize: 13,
  },
  msgTooltipDivider: {
    width: 1,
    height: 14,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 2,
  },
  msgTooltipActionBtn: {
    width: 22,
    height: 22,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  msgTooltipActionBtnDanger: {
    backgroundColor: '#FEF2F2',
  },
  // Native Telegram Desktop Right-Click Context Menu
  tgContextMenuBackdrop: {
    ...({
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 9998,
      backgroundColor: 'transparent',
    } as any),
  },
  tgContextMenu: {
    ...({
      position: 'fixed',
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#CBD5E1',
      borderRadius: 10,
      padding: 6,
      minWidth: 210,
      zIndex: 9999,
      gap: 2,
    } as any),
  },
  tgContextMenuReactionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 7,
    paddingHorizontal: 6,
    paddingVertical: 4,
    marginBottom: 4,
  },
  tgContextReactionBtn: {
    padding: 3,
    borderRadius: 4,
  },
  tgContextReactionText: {
    fontSize: 14,
  },
  tgContextMenuDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: 3,
  },
  tgContextMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  tgContextMenuItemDanger: {
    backgroundColor: '#FEF2F2',
  },
  tgContextItemText: {
    fontSize: 11.5,
    fontFamily: 'Krasar-Regular',
    color: '#334155',
  },
  tgContextItemTextDanger: {
    color: '#EF4444',
  },
});
